package com.xtramile.patientcrud.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.*;
import java.time.LocalDate;

@Document(collection = "patients")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Patient {

    @Id
    private String id;  // MongoDB autogenerated ObjectId

    @NonNull
    private String firstName;

    @NonNull
    private String lastName;
    
    private LocalDate dateOfBirth;
    
    private String gender;
    
    // Embedded Australian Address document
    private Address address;
    
    private String phoneNo;
}
